import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const B_Mitra = localFont({
  src: "./fonts/B Mitra_YasDL.com.ttf",
  variable: "--font-B_Mitra",
  weight: "100 900",
});
const B_Narm = localFont({
  src: "./fonts/B Narm_YasDL.com.ttf",
  variable: "--font-B_Narm",
  weight: "100 900",
});
const B_Nazanin = localFont({
  src: "./fonts/B Nazanin Bold_YasDL.com.ttf",
  variable: "--font-B_Nazanin",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}
        ${B_Narm.variable}
        ${B_Nazanin.variable}

         ${geistMono.variable} ${B_Mitra.variable}  antialiased`}
      >
        <HeroUIProvider>{children}</HeroUIProvider>
      </body>
    </html>
  );
}
